server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    enable:
      jvm: true
      logback: true
      system: true