/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package org.example

import spock.lang.Specification

class AppTest extends Specification {
    def "application has a test"() {
        expect:
        "TODO" != "DONE"
    }
}
